--
-- PostgreSQL database dump
--

-- Dumped from database version 12.1
-- Dumped by pg_dump version 12.1

-- Started on 2019-11-23 14:56:02

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 203 (class 1259 OID 16576)
-- Name: accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts
(
    id           bigint NOT NULL,
    address      character varying(255),
    first_name   character varying(255),
    last_name    character varying(255),
    patronymic   character varying(255),
    phone_number character varying(255),
    photo_uri    character varying(255),
    username     character varying(255)
);


ALTER TABLE public.accounts
    OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 16574)
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public .accounts_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );


--
-- TOC entry 225 (class 1259 OID 16837)
-- Name: authorities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authorities
(
    username  character varying(256) NOT NULL,
    authority character varying(256) NOT NULL
);


ALTER TABLE public.authorities
    OWNER TO postgres;

--
-- TOC entry 205 (class 1259 OID 16586)
-- Name: authors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authors
(
    id          bigint NOT NULL,
    first_name  character varying(255),
    second_name character varying(255)
);


ALTER TABLE public.authors
    OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 16584)
-- Name: authors_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authors
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public .authors_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );


--
-- TOC entry 207 (class 1259 OID 16596)
-- Name: books; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.books
(
    id                  bigint           NOT NULL,
    name                character varying(255),
    picture_uri         character varying(255),
    price               double precision NOT NULL,
    year_of_publication integer          NOT NULL
);


ALTER TABLE public.books
    OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 16604)
-- Name: books_authors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.books_authors
(
    book_id   bigint NOT NULL,
    author_id bigint NOT NULL
);


ALTER TABLE public.books_authors
    OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 16609)
-- Name: books_genres; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.books_genres
(
    book_id  bigint NOT NULL,
    genre_id bigint NOT NULL
);


ALTER TABLE public.books_genres
    OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 16594)
-- Name: books_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.books
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public .books_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );


--
-- TOC entry 211 (class 1259 OID 16616)
-- Name: genres; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.genres
(
    id   bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.genres
    OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 16614)
-- Name: genres_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.genres
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public .genres_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );


--
-- TOC entry 220 (class 1259 OID 16790)
-- Name: oauth_access_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oauth_access_token
(
    token_id          character varying(256),
    token             bytea,
    authentication_id character varying(256),
    user_name         character varying(256),
    client_id         character varying(256),
    authentication    bytea,
    refresh_token     character varying(256)
);


ALTER TABLE public.oauth_access_token
    OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16808)
-- Name: oauth_approvals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oauth_approvals
(
    userid         character varying(256),
    clientid       character varying(256),
    scope          character varying(256),
    status         character varying(10),
    expiresat      timestamp without time zone,
    lastmodifiedat timestamp without time zone
);


ALTER TABLE public.oauth_approvals
    OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16776)
-- Name: oauth_client_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oauth_client_details
(
    client_id               character varying(256) NOT NULL,
    resource_ids            character varying(256),
    client_secret           character varying(256),
    scope                   character varying(256),
    authorized_grant_types  character varying(256),
    web_server_redirect_uri character varying(256),
    authorities             character varying(256),
    access_token_validity   integer,
    refresh_token_validity  integer,
    additional_information  character varying(4096),
    autoapprove             character varying(256)
);


ALTER TABLE public.oauth_client_details
    OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16784)
-- Name: oauth_client_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oauth_client_token
(
    token_id          character varying(256),
    token             bytea,
    authentication_id character varying(256),
    user_name         character varying(256),
    client_id         character varying(256)
);


ALTER TABLE public.oauth_client_token
    OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16802)
-- Name: oauth_code; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oauth_code
(
    code           character varying(256),
    authentication bytea
);


ALTER TABLE public.oauth_code
    OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16796)
-- Name: oauth_refresh_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oauth_refresh_token
(
    token_id       character varying(256),
    token          bytea,
    authentication bytea
);


ALTER TABLE public.oauth_refresh_token
    OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 16623)
-- Name: order_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_details
(
    id       bigint  NOT NULL,
    quantity integer NOT NULL,
    book_id  bigint,
    order_id bigint
);


ALTER TABLE public.order_details
    OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 16621)
-- Name: order_details_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_details
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public .order_details_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );


--
-- TOC entry 215 (class 1259 OID 16630)
-- Name: order_statuses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_statuses
(
    id   integer NOT NULL,
    name character varying(255)
);


ALTER TABLE public.order_statuses
    OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 16628)
-- Name: order_statuses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_statuses
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public .order_statuses_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );


--
-- TOC entry 217 (class 1259 OID 16637)
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders
(
    id               bigint NOT NULL,
    customer_address character varying(255),
    customer_name    character varying(255),
    customer_phone   character varying(255),
    order_date_time  timestamp without time zone,
    username         character varying(255),
    order_status_id  integer
);


ALTER TABLE public.orders
    OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16635)
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public .orders_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );


--
-- TOC entry 224 (class 1259 OID 16829)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users
(
    username character varying(256) NOT NULL,
    password character varying(256) NOT NULL,
    enabled  boolean                NOT NULL
);


ALTER TABLE public.users
    OWNER TO postgres;

--
-- TOC entry 2776 (class 2606 OID 16583)
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- TOC entry 2780 (class 2606 OID 16593)
-- Name: authors authors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authors
    ADD CONSTRAINT authors_pkey PRIMARY KEY (id);


--
-- TOC entry 2784 (class 2606 OID 16608)
-- Name: books_authors books_authors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.books_authors
    ADD CONSTRAINT books_authors_pkey PRIMARY KEY (book_id, author_id);


--
-- TOC entry 2786 (class 2606 OID 16613)
-- Name: books_genres books_genres_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.books_genres
    ADD CONSTRAINT books_genres_pkey PRIMARY KEY (book_id, genre_id);


--
-- TOC entry 2782 (class 2606 OID 16603)
-- Name: books books_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);


--
-- TOC entry 2788 (class 2606 OID 16620)
-- Name: genres genres_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.genres
    ADD CONSTRAINT genres_pkey PRIMARY KEY (id);


--
-- TOC entry 2798 (class 2606 OID 16783)
-- Name: oauth_client_details oauth_client_details_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth_client_details
    ADD CONSTRAINT oauth_client_details_pkey PRIMARY KEY (client_id);


--
-- TOC entry 2790 (class 2606 OID 16627)
-- Name: order_details order_details_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT order_details_pkey PRIMARY KEY (id);


--
-- TOC entry 2792 (class 2606 OID 16634)
-- Name: order_statuses order_statuses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_statuses
    ADD CONSTRAINT order_statuses_pkey PRIMARY KEY (id);


--
-- TOC entry 2796 (class 2606 OID 16644)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- TOC entry 2778 (class 2606 OID 16646)
-- Name: accounts uk_k8h1bgqoplx0rkngj01pm1rgp; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT uk_k8h1bgqoplx0rkngj01pm1rgp UNIQUE (username);


--
-- TOC entry 2794 (class 2606 OID 16648)
-- Name: order_statuses uk_p14tnvp6d460yt9akmq14bigx; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_statuses
    ADD CONSTRAINT uk_p14tnvp6d460yt9akmq14bigx UNIQUE (name);


--
-- TOC entry 2800 (class 2606 OID 16836)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (username);


--
-- TOC entry 2801 (class 1259 OID 16848)
-- Name: ix_auth_username; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX ix_auth_username ON public.authorities USING btree (username, authority);


--
-- TOC entry 2803 (class 2606 OID 16654)
-- Name: books_authors fk1b933slgixbjdslgwu888m34v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.books_authors
    ADD CONSTRAINT fk1b933slgixbjdslgwu888m34v FOREIGN KEY (book_id) REFERENCES public.books (id);


--
-- TOC entry 2802 (class 2606 OID 16649)
-- Name: books_authors fk3qua08pjd1ca1fe2x5cgohuu5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.books_authors
    ADD CONSTRAINT fk3qua08pjd1ca1fe2x5cgohuu5 FOREIGN KEY (author_id) REFERENCES public.authors (id);


--
-- TOC entry 2809 (class 2606 OID 16843)
-- Name: authorities fk_authorities_users; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authorities
    ADD CONSTRAINT fk_authorities_users FOREIGN KEY (username) REFERENCES public.users (username);


--
-- TOC entry 2808 (class 2606 OID 16679)
-- Name: orders fkcbbqf26brulgfgvd0mf74rv4y; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkcbbqf26brulgfgvd0mf74rv4y FOREIGN KEY (order_status_id) REFERENCES public.order_statuses (id);


--
-- TOC entry 2804 (class 2606 OID 16659)
-- Name: books_genres fkgkat05y2cec3tcpl6ur250sd0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.books_genres
    ADD CONSTRAINT fkgkat05y2cec3tcpl6ur250sd0 FOREIGN KEY (genre_id) REFERENCES public.genres (id);


--
-- TOC entry 2806 (class 2606 OID 16669)
-- Name: order_details fkjqe04yonp6a52rhbf2y0m03qw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT fkjqe04yonp6a52rhbf2y0m03qw FOREIGN KEY (book_id) REFERENCES public.books (id);


--
-- TOC entry 2807 (class 2606 OID 16674)
-- Name: order_details fkjyu2qbqt8gnvno9oe9j2s2ldk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT fkjyu2qbqt8gnvno9oe9j2s2ldk FOREIGN KEY (order_id) REFERENCES public.orders (id);


--
-- TOC entry 2805 (class 2606 OID 16664)
-- Name: books_genres fklv42b6uemg63q27om39jjbt9o; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.books_genres
    ADD CONSTRAINT fklv42b6uemg63q27om39jjbt9o FOREIGN KEY (book_id) REFERENCES public.books (id);


-- Completed on 2019-11-23 14:56:02

--
-- PostgreSQL database dump complete
--